spring:
  application:
    name: bigdata-back
  data:
    mongodb:
      uri: mongodb://localhost:27017/amazon_reviews
      database: amazon_reviews
      auto-index-creation: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
            repository:
              Query: DEBUG
    com:
      example:
        bigdataback: DEBUG

server:
  port: 9999
  servlet:
    context-path: /api/v1
