import { Product } from '../types';

export const mockProducts: Product[] = [
    {
        main_category: 'All Beauty',
        title: 'Howard LC0008 Leather Conditioner, 8-Ounce (4-Pack)',
        average_rating: 4.8,
        rating_number: 10,
        features: [],
        description: ['Description du produit'],
        price: null,
        images: [
            { thumb: 'https://m.media-amazon.com/images/I/41qfjSfqNyL._SS40_.jpg', large: 'https://m.media-amazon.com/images/I/41qfjSfqNyL.jpg', variant: 'MAIN', hi_res: null },
            {
                thumb: 'https://m.media-amazon.com/images/I/41w2yznfuZL._SS40_.jpg',
                large: 'https://m.media-amazon.com/images/I/41w2yznfuZL.jpg',
                variant: 'PT01',
                hi_res: 'https://m.media-amazon.com/images/I/71i77AuI9xL._SL1500_.jpg',
            },
        ],
        videos: [],
        store: 'Howard Products',
        categories: [],
        details: { 'Package Dimensions': '7.1 x 5.5 x 3 inches; 2.38 Pounds', UPC: '617390882781' },
        parent_asin: 'B01CUPMQZE',
        bought_together: null,
    },
    {
        main_category: 'All Beauty',
        title: 'Yes to Tomatoes Detoxifying Charcoal Cleanser (Pack of 2) with Charcoal Powder, Tomato Fruit Extract, and Gingko Biloba Leaf Extract, 5 fl. oz.',
        average_rating: 4.5,
        rating_number: 3,
        features: [],
        description: [],
        price: null,
        images: [
            {
                thumb: 'https://m.media-amazon.com/images/I/41b+11d5igL._SS40_.jpg',
                large: 'https://m.media-amazon.com/images/I/41b+11d5igL.jpg',
                variant: 'MAIN',
                hi_res: 'https://m.media-amazon.com/images/I/71g1lP0pMbL._SL1500_.jpg',
            },
            {
                thumb: 'https://m.media-amazon.com/images/I/41j2ocUzCtL._SS40_.jpg',
                large: 'https://m.media-amazon.com/images/I/41j2ocUzCtL.jpg',
                variant: 'PT01',
                hi_res: 'https://m.media-amazon.com/images/I/81OqvR94isL._SL1500_.jpg',
            },
        ],
        videos: [],
        store: 'Yes To',
        categories: [],
        details: {
            'Item Form': 'Powder',
            'Skin Type': 'Acne Prone',
            Brand: 'Yes To',
            'Age Range (Description)': 'Adult',
            'Unit Count': '10 Fl Oz',
            'Is Discontinued By Manufacturer': 'No',
            'Item model number': 'SG_B076WQZGPM_US',
            UPC: '653801351125',
            Manufacturer: 'Yes to Tomatoes',
        },
        parent_asin: 'B076WQZGPM',
        bought_together: null,
    },
    {
        main_category: 'All Beauty',
        title: 'Eye Patch Black Adult with Tie Band (6 Per Pack)',
        average_rating: 4.4,
        rating_number: 26,
        features: [],
        description: [],
        price: null,
        images: [
            { thumb: 'https://m.media-amazon.com/images/I/31bz+uqzWCL._SS40_.jpg', large: 'https://m.media-amazon.com/images/I/31bz+uqzWCL.jpg', variant: 'MAIN', hi_res: null },
            { thumb: 'https://m.media-amazon.com/images/I/31bz+uqzWCL._SS40_.jpg', large: 'https://m.media-amazon.com/images/I/31bz+uqzWCL.jpg', variant: 'PT01', hi_res: null },
        ],
        videos: [],
        store: 'Levine Health Products',
        categories: [],
        details: { Manufacturer: 'Levine Health Products' },
        parent_asin: 'B000B658RI',
        bought_together: null,
    },
    {
        main_category: 'All Beauty',
        title: 'Tattoo Eyebrow Stickers, Waterproof Eyebrow, 4D Imitation Eyebrow Tattoos, 4D Hair-like Authentic Eyebrows Waterproof Long Lasting for Woman & Man Makeup Tool',
        average_rating: 3.1,
        rating_number: 102,
        features: [],
        description: [],
        price: null,
        images: [
            {
                thumb: 'https://m.media-amazon.com/images/I/515iwxdKS1L._SS40_.jpg',
                large: 'https://m.media-amazon.com/images/I/515iwxdKS1L.jpg',
                variant: 'MAIN',
                hi_res: 'https://m.media-amazon.com/images/I/71GJhXQGvyL._SL1500_.jpg',
            },
            {
                thumb: 'https://m.media-amazon.com/images/I/51ALSVnGDML._SS40_.jpg',
                large: 'https://m.media-amazon.com/images/I/51ALSVnGDML.jpg',
                variant: 'PT01',
                hi_res: 'https://m.media-amazon.com/images/I/61NS1lONhzL._SL1001_.jpg',
            },
            {
                thumb: 'https://m.media-amazon.com/images/I/51GvPall-ML._SS40_.jpg',
                large: 'https://m.media-amazon.com/images/I/51GvPall-ML.jpg',
                variant: 'PT02',
                hi_res: 'https://m.media-amazon.com/images/I/61lcwXtw3ZL._SL1001_.jpg',
            },
            {
                thumb: 'https://m.media-amazon.com/images/I/51JFEUql-KL._SS40_.jpg',
                large: 'https://m.media-amazon.com/images/I/51JFEUql-KL.jpg',
                variant: 'PT03',
                hi_res: 'https://m.media-amazon.com/images/I/61G-iZeX-LL._SL1001_.jpg',
            },
            {
                thumb: 'https://m.media-amazon.com/images/I/414rIT4vNAL._SS40_.jpg',
                large: 'https://m.media-amazon.com/images/I/414rIT4vNAL.jpg',
                variant: 'PT04',
                hi_res: 'https://m.media-amazon.com/images/I/618BBBsAQrL._SL1001_.jpg',
            },
            {
                thumb: 'https://m.media-amazon.com/images/I/41JVLUdtYaL._SS40_.jpg',
                large: 'https://m.media-amazon.com/images/I/41JVLUdtYaL.jpg',
                variant: 'PT05',
                hi_res: 'https://m.media-amazon.com/images/I/61iomcZjbAL._SL1001_.jpg',
            },
            {
                thumb: 'https://m.media-amazon.com/images/I/51Vxn6nVrVL._SS40_.jpg',
                large: 'https://m.media-amazon.com/images/I/51Vxn6nVrVL.jpg',
                variant: 'PT06',
                hi_res: 'https://m.media-amazon.com/images/I/61m-71vCbCL._SL1001_.jpg',
            },
        ],
        videos: [],
        store: 'Cherioll',
        categories: [],
        details: {
            Brand: 'Cherioll',
            'Item Form': 'Powder',
            'Finish Type': 'Natural',
            'Product Benefits': 'Long Lasting',
            'Skin Type': 'All',
            'Package Dimensions': '8.43 x 5.91 x 0.87 inches; 8.78 Ounces',
            'Item model number': 'eyebrow sticker001',
        },
        parent_asin: 'B088FKY3VD',
        bought_together: null,
    },
];
