import { Review } from '../types';

export const mockReviews: Review[] = [
    {
        rating: 5.0,
        title: 'Such a lovely scent but not overpowering.',
        text: "This spray is really nice. It smells really good, goes on really fine, and does the trick. I will say it feels like you need a lot of it though to get the texture I want. I have a lot of hair, medium thickness. I am comparing to other brands with yucky chemicals so I'm gonna stick with this. Try it!",
        images: [],
        asin: 'B00YQ6X8EO',
        parent_asin: 'B00YQ6X8EO',
        user_id: 'AGKHLEW2SOWHNMFQIJGBECAF7INQ',
        timestamp: 1588687728923,
        helpful_vote: 0,
        verified_purchase: true,
    },
    {
        rating: 4.0,
        title: 'Works great but smells a little weird.',
        text: 'This product does what I need it to do, I just wish it was odorless or had a soft coconut smell. Having my head smell like an orange coffee is offputting. (granted, I did know the smell was described but I was hoping it would be light)',
        images: [],
        asin: 'B081TJ8YS3',
        parent_asin: 'B081TJ8YS3',
        user_id: 'AGKHLEW2SOWHNMFQIJGBECAF7INQ',
        timestamp: 1588615855070,
        helpful_vote: 1,
        verified_purchase: true,
    },
    {
        rating: 5.0,
        title: 'Yes!',
        text: 'Smells good, feels great!',
        images: [],
        asin: 'B07PNNCSP9',
        parent_asin: 'B097R46CSY',
        user_id: 'AE74DYR3QUGVPZJ3P7RFWBGIX7XQ',
        timestamp: 1589665266052,
        helpful_vote: 2,
        verified_purchase: true,
    },
    {
        rating: 1.0,
        title: 'Synthetic feeling',
        text: 'Felt synthetic',
        images: [],
        asin: 'B09JS339BZ',
        parent_asin: 'B09JS339BZ',
        user_id: 'AFQLNQNQYFWQZPJQZS6V3NZU4QBQ',
        timestamp: 1643393630220,
        helpful_vote: 0,
        verified_purchase: true,
    },
    {
        rating: 5.0,
        title: 'A+',
        text: 'Love it',
        images: [],
        asin: 'B08BZ63GMJ',
        parent_asin: 'B08BZ63GMJ',
        user_id: 'AFQLNQNQYFWQZPJQZS6V3NZU4QBQ',
        timestamp: 1609322563534,
        helpful_vote: 0,
        verified_purchase: true,
    },
    {
        rating: 4.0,
        title: 'Pretty Color',
        text: 'The polish was quiet thick and did not apply smoothly. I let dry overnight before adding a second coat since it was so thick.',
        images: [
            {
                small_image_url: 'https://images-na.ssl-images-amazon.com/images/I/71e9Noi7dJL._SL256_.jpg',
                medium_image_url: 'https://images-na.ssl-images-amazon.com/images/I/71e9Noi7dJL._SL800_.jpg',
                large_image_url: 'https://images-na.ssl-images-amazon.com/images/I/71e9Noi7dJL._SL1600_.jpg',
                attachment_type: 'IMAGE',
            },
        ],
        asin: 'B00R8DXL44',
        parent_asin: 'B00R8DXL44',
        user_id: 'AGMJ3EMDVL6OWBJF7CA5RGJLXN5A',
        timestamp: 1598567408138,
        helpful_vote: 0,
        verified_purchase: false,
    },
    {
        rating: 5.0,
        title: 'Handy',
        text: 'Great for many tasks.  I purchased these for makeup removal.  No makeup on your washcloths.  Disposable, so great for travel.  Soft.  Absorbant.',
        images: [],
        asin: 'B099DRHW5V',
        parent_asin: 'B099DRHW5V',
        user_id: 'AHREXOGQPZDA6354MHH4ETSF3MCQ',
        timestamp: 1631885519443,
        helpful_vote: 0,
        verified_purchase: false,
    },
    {
        rating: 3.0,
        title: 'Meh',
        text: 'These were lightweight and soft but much too small for my liking. I would have preferred two of these together to make one loc. For that reason I will not be repurchasing.',
        images: [
            {
                small_image_url: 'https://m.media-amazon.com/images/I/81FN4c0VHzL._SL256_.jpg',
                medium_image_url: 'https://m.media-amazon.com/images/I/81FN4c0VHzL._SL800_.jpg',
                large_image_url: 'https://m.media-amazon.com/images/I/81FN4c0VHzL._SL1600_.jpg',
                attachment_type: 'IMAGE',
            },
        ],
        asin: 'B088SZDGXG',
        parent_asin: 'B08BBQ29N5',
        user_id: 'AEYORY2AVPMCPDV57CE337YU5LXA',
        timestamp: 1634275259292,
        helpful_vote: 0,
        verified_purchase: true,
    },
];
